name: Build
on: workflow_dispatch
jobs:
  build-wheel:
    runs-on: ubuntu-latest
    container: buildpack-deps:buster
    outputs:
      wheel-artifact-id: ${{ steps.upload-wheel.outputs.artifact-id }}
    steps:
      - name: Update apt sources
        run: sed -i 's/deb\.debian/archive\.debian/g' /etc/apt/sources.list
      - name: Install dependencies
        run: apt-get update && apt-get install -y --no-install-recommends python-packaging python-pip python-setuptools python-toml python-typing python-wheel && python2 -m pip install --disable-pip-version-check --no-cache-dir build==0.5.1 importlib-metadata==0.22 pep517==0.12.0 virtualenv==20.15.1
      - name: Checkout
        uses: actions/checkout@v6
      - name: Build
        run: python2 -m build
      - name: Upload sdist artifact
        uses: actions/upload-artifact@v7
        with:
          path: dist/pybitmessage*.tar.gz
          archive: false
      - name: Upload wheel artifact
        uses: actions/upload-artifact@v7
        id: upload-wheel
        with:
          path: dist/pybitmessage*.whl
          archive: false
  build-appimage:
    needs: build-wheel
    runs-on: ubuntu-latest
    container: debian:buster
    steps:
      - name: Download wheel artifact
        uses: actions/download-artifact@v8
        with:
          artifact-ids: ${{needs.build-wheel.outputs.wheel-artifact-id}}
      - name: Update apt sources
        run: sed -i 's/deb\.debian/archive\.debian/g' /etc/apt/sources.list
      - name: Install dependencies
        run: apt-get update && apt-get install -y --no-install-recommends gtk-update-icon-cache python-pip python-setuptools python-six python-wheel wget && python2 -m pip install --disable-pip-version-check --no-cache-dir --prefix=/usr --root=AppDir pybitmessage*.whl
      - name: Checkout
        uses: actions/checkout@v6
        with:
          path: src
      - name: Download AppImage-Builder
        run: wget -qO appimage-builder.AppImage https://github.com/AppImageCrafters/appimage-builder/releases/download/v1.1.0/appimage-builder-1.1.0-x86_64.AppImage && chmod +x appimage-builder.AppImage
      - name: Build AppImage
        env:
          ARCH: amd64
          APPIMAGE_ARCH: x86_64
          RUNTIME: x86_64
          APP_VERSION: 0.6.3.2
        run: ./appimage-builder.AppImage --appimage-extract-and-run --log INFO --recipe src/AppImageBuilder.yml
      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          path: PyBitmessage*.AppImage
          archive: false
